//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Guardtime.KSI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Guardtime.KSI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/testdata.txt.
        /// </summary>
        internal static string DataHasher_TestFile {
            get {
                return ResourceManager.GetString("DataHasher_TestFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LongString1ReallyLongString2EvenLongerString3.
        /// </summary>
        internal static string DataHasher_TestString {
            get {
                return ResourceManager.GetString("DataHasher_TestString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/publication/publicationdata/publicationdata.tlv.
        /// </summary>
        internal static string PublicationData_CorrectStructureFile {
            get {
                return ResourceManager.GetString("PublicationData_CorrectStructureFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/publication/publicationdata/missingtag.tlv.
        /// </summary>
        internal static string PublicationData_MissingTagFile {
            get {
                return ResourceManager.GetString("PublicationData_MissingTagFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/publication/publicationdata/noncriticaltag.tlv.
        /// </summary>
        internal static string PublicationData_NonCriticalTagFile {
            get {
                return ResourceManager.GetString("PublicationData_NonCriticalTagFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/publication/publicationdata/unknowntag.tlv.
        /// </summary>
        internal static string PublicationData_UnknownTagFile {
            get {
                return ResourceManager.GetString("PublicationData_UnknownTagFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/signaturedata/signature-data-invalid-certificate-id-missing.tlv.
        /// </summary>
        internal static string SignatureData_Invalid_Certificate_Id_Missing {
            get {
                return ResourceManager.GetString("SignatureData_Invalid_Certificate_Id_Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/signaturedata/signature-data-invalid-extra-tag.tlv.
        /// </summary>
        internal static string SignatureData_Invalid_Extra_Tag {
            get {
                return ResourceManager.GetString("SignatureData_Invalid_Extra_Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/signaturedata/signature-data-invalid-multiple-certificate-id.tlv.
        /// </summary>
        internal static string SignatureData_Invalid_Multiple_Certificate_Id {
            get {
                return ResourceManager.GetString("SignatureData_Invalid_Multiple_Certificate_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/signaturedata/signature-data-invalid-multiple-certificate-rep-uri.tlv.
        /// </summary>
        internal static string SignatureData_Invalid_Multiple_Certificate_Rep_Uri {
            get {
                return ResourceManager.GetString("SignatureData_Invalid_Multiple_Certificate_Rep_Uri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/signaturedata/signature-data-invalid-multiple-type.tlv.
        /// </summary>
        internal static string SignatureData_Invalid_Multiple_Signature_Type {
            get {
                return ResourceManager.GetString("SignatureData_Invalid_Multiple_Signature_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/signaturedata/signature-data-invalid-multiple-value.tlv.
        /// </summary>
        internal static string SignatureData_Invalid_Multiple_Signature_Value {
            get {
                return ResourceManager.GetString("SignatureData_Invalid_Multiple_Signature_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/signaturedata/signature-data-invalid-type-missing.tlv.
        /// </summary>
        internal static string SignatureData_Invalid_Signature_Type_Missing {
            get {
                return ResourceManager.GetString("SignatureData_Invalid_Signature_Type_Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/signaturedata/signature-data-invalid-value-missing.tlv.
        /// </summary>
        internal static string SignatureData_Invalid_Signature_Value_Missing {
            get {
                return ResourceManager.GetString("SignatureData_Invalid_Signature_Value_Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/signaturedata/signature-data-invalid-type.tlv.
        /// </summary>
        internal static string SignatureData_Invalid_Wrong_Type {
            get {
                return ResourceManager.GetString("SignatureData_Invalid_Wrong_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/signaturedata/signature-data-ok.tlv.
        /// </summary>
        internal static string SignatureData_Ok {
            get {
                return ResourceManager.GetString("SignatureData_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/signaturedata/signature-data-ok-no-uri.tlv.
        /// </summary>
        internal static string SignatureData_Ok_No_Uri {
            get {
                return ResourceManager.GetString("SignatureData_Ok_No_Uri", resourceCulture);
            }
        }
    }
}
