//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Guardtime.KSI.Test.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Guardtime.KSI.Test.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/aggregation-authentication-record/aggregation-authentication-record-invalid-extra-tag.tlv.
        /// </summary>
        internal static string AggregationAuthenticationRecord_Invalid_Extra_Tag {
            get {
                return ResourceManager.GetString("AggregationAuthenticationRecord_Invalid_Extra_Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/aggregation-authentication-record/aggregation-authentication-record-invalid-missing-aggregation-time.tlv.
        /// </summary>
        internal static string AggregationAuthenticationRecord_Invalid_Missing_Aggregation_Time {
            get {
                return ResourceManager.GetString("AggregationAuthenticationRecord_Invalid_Missing_Aggregation_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/aggregation-authentication-record/aggregation-authentication-record-invalid-missing-chain-index.tlv.
        /// </summary>
        internal static string AggregationAuthenticationRecord_Invalid_Missing_Chain_Index {
            get {
                return ResourceManager.GetString("AggregationAuthenticationRecord_Invalid_Missing_Chain_Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/aggregation-authentication-record/aggregation-authentication-record-invalid-missing-input-hash.tlv.
        /// </summary>
        internal static string AggregationAuthenticationRecord_Invalid_Missing_Input_Hash {
            get {
                return ResourceManager.GetString("AggregationAuthenticationRecord_Invalid_Missing_Input_Hash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/aggregation-authentication-record/aggregation-authentication-record-invalid-missing-signature-data.tlv.
        /// </summary>
        internal static string AggregationAuthenticationRecord_Invalid_Missing_Signature_Data {
            get {
                return ResourceManager.GetString("AggregationAuthenticationRecord_Invalid_Missing_Signature_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/aggregation-authentication-record/aggregation-authentication-record-invalid-multiple-aggregation-time.tlv.
        /// </summary>
        internal static string AggregationAuthenticationRecord_Invalid_Multiple_Aggregation_Time {
            get {
                return ResourceManager.GetString("AggregationAuthenticationRecord_Invalid_Multiple_Aggregation_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/aggregation-authentication-record/aggregation-authentication-record-invalid-multiple-input-hash.tlv.
        /// </summary>
        internal static string AggregationAuthenticationRecord_Invalid_Multiple_Input_Hash {
            get {
                return ResourceManager.GetString("AggregationAuthenticationRecord_Invalid_Multiple_Input_Hash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/aggregation-authentication-record/aggregation-authentication-record-invalid-multiple-signature-data.tlv.
        /// </summary>
        internal static string AggregationAuthenticationRecord_Invalid_Multiple_Signature_Data {
            get {
                return ResourceManager.GetString("AggregationAuthenticationRecord_Invalid_Multiple_Signature_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/aggregation-authentication-record/aggregation-authentication-record-invalid-type.tlv.
        /// </summary>
        internal static string AggregationAuthenticationRecord_Invalid_Type {
            get {
                return ResourceManager.GetString("AggregationAuthenticationRecord_Invalid_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/aggregation-authentication-record/aggregation-authentication-record-ok.tlv.
        /// </summary>
        internal static string AggregationAuthenticationRecord_Ok {
            get {
                return ResourceManager.GetString("AggregationAuthenticationRecord_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/aggregation-hash-chain/aggregation-hash-chain-invalid-extra-tag.tlv.
        /// </summary>
        internal static string AggregationHashChain_Invalid_Extra_Tag {
            get {
                return ResourceManager.GetString("AggregationHashChain_Invalid_Extra_Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/aggregation-hash-chain/aggregation-hash-chain-invalid-missing-aggregation-algorithm.tlv.
        /// </summary>
        internal static string AggregationHashChain_Invalid_Missing_Aggregation_Algorithm {
            get {
                return ResourceManager.GetString("AggregationHashChain_Invalid_Missing_Aggregation_Algorithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/aggregation-hash-chain/aggregation-hash-chain-invalid-missing-aggregation-time.tlv.
        /// </summary>
        internal static string AggregationHashChain_Invalid_Missing_Aggregation_Time {
            get {
                return ResourceManager.GetString("AggregationHashChain_Invalid_Missing_Aggregation_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/aggregation-hash-chain/aggregation-hash-chain-invalid-missing-chain-index.tlv.
        /// </summary>
        internal static string AggregationHashChain_Invalid_Missing_Chain_Index {
            get {
                return ResourceManager.GetString("AggregationHashChain_Invalid_Missing_Chain_Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/aggregation-hash-chain/aggregation-hash-chain-invalid-missing-input-hash.tlv.
        /// </summary>
        internal static string AggregationHashChain_Invalid_Missing_Input_Hash {
            get {
                return ResourceManager.GetString("AggregationHashChain_Invalid_Missing_Input_Hash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/aggregation-hash-chain/aggregation-hash-chain-invalid-missing-links.tlv.
        /// </summary>
        internal static string AggregationHashChain_Invalid_Missing_Links {
            get {
                return ResourceManager.GetString("AggregationHashChain_Invalid_Missing_Links", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/aggregation-hash-chain/aggregation-hash-chain-invalid-multiple-aggregation-algorithm.tlv.
        /// </summary>
        internal static string AggregationHashChain_Invalid_Multiple_Aggregation_Algorithm {
            get {
                return ResourceManager.GetString("AggregationHashChain_Invalid_Multiple_Aggregation_Algorithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/aggregation-hash-chain/aggregation-hash-chain-invalid-multiple-aggregation-time.tlv.
        /// </summary>
        internal static string AggregationHashChain_Invalid_Multiple_Aggregation_Time {
            get {
                return ResourceManager.GetString("AggregationHashChain_Invalid_Multiple_Aggregation_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/aggregation-hash-chain/aggregation-hash-chain-invalid-multiple-input-data.tlv.
        /// </summary>
        internal static string AggregationHashChain_Invalid_Multiple_Input_Data {
            get {
                return ResourceManager.GetString("AggregationHashChain_Invalid_Multiple_Input_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/aggregation-hash-chain/aggregation-hash-chain-invalid-multiple-input-hash.tlv.
        /// </summary>
        internal static string AggregationHashChain_Invalid_Multiple_Input_Hash {
            get {
                return ResourceManager.GetString("AggregationHashChain_Invalid_Multiple_Input_Hash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/aggregation-hash-chain/aggregation-hash-chain-invalid-type.tlv.
        /// </summary>
        internal static string AggregationHashChain_Invalid_Type {
            get {
                return ResourceManager.GetString("AggregationHashChain_Invalid_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/aggregation-hash-chain/aggregation-hash-chain-link-invalid-all-tags-exist.tlv.
        /// </summary>
        internal static string AggregationHashChain_Link_Invalid_All_Tags_Defined {
            get {
                return ResourceManager.GetString("AggregationHashChain_Link_Invalid_All_Tags_Defined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/aggregation-hash-chain/aggregation-hash-chain-link-invalid-empty.tlv.
        /// </summary>
        internal static string AggregationHashChain_Link_Invalid_Empty {
            get {
                return ResourceManager.GetString("AggregationHashChain_Link_Invalid_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/aggregation-hash-chain/aggregation-hash-chain-link-invalid-extra-tag.tlv.
        /// </summary>
        internal static string AggregationHashChain_Link_Invalid_Extra_Tag {
            get {
                return ResourceManager.GetString("AggregationHashChain_Link_Invalid_Extra_Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/aggregation-hash-chain/aggregation-hash-chain-link-invalid-metadata-metahash-no-siblinghash.tlv.
        /// </summary>
        internal static string AggregationHashChain_Link_Invalid_Metadata_Metahash_No_SiblingHash {
            get {
                return ResourceManager.GetString("AggregationHashChain_Link_Invalid_Metadata_Metahash_No_SiblingHash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/aggregation-hash-chain/aggregation-hash-chain-link-invalid-multiple-levelcorrection.tlv.
        /// </summary>
        internal static string AggregationHashChain_Link_Invalid_Multiple_LevelCorrection {
            get {
                return ResourceManager.GetString("AggregationHashChain_Link_Invalid_Multiple_LevelCorrection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/aggregation-hash-chain/aggregation-hash-chain-link-invalid-multiple-metadata.tlv.
        /// </summary>
        internal static string AggregationHashChain_Link_Invalid_Multiple_Metadata {
            get {
                return ResourceManager.GetString("AggregationHashChain_Link_Invalid_Multiple_Metadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/aggregation-hash-chain/aggregation-hash-chain-link-invalid-multiple-metahash.tlv.
        /// </summary>
        internal static string AggregationHashChain_Link_Invalid_Multiple_Metahash {
            get {
                return ResourceManager.GetString("AggregationHashChain_Link_Invalid_Multiple_Metahash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/aggregation-hash-chain/aggregation-hash-chain-link-invalid-multiple-siblinghash.tlv.
        /// </summary>
        internal static string AggregationHashChain_Link_Invalid_Multiple_Siblinghash {
            get {
                return ResourceManager.GetString("AggregationHashChain_Link_Invalid_Multiple_Siblinghash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/aggregation-hash-chain/aggregation-hash-chain-link-invalid-sibling-metadata-no-metahash.tlv.
        /// </summary>
        internal static string AggregationHashChain_Link_Invalid_SiblingHash_Metadata_No_MetaHash {
            get {
                return ResourceManager.GetString("AggregationHashChain_Link_Invalid_SiblingHash_Metadata_No_MetaHash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/aggregation-hash-chain/aggregation-hash-chain-link-invalid-sibling-metahash-and-no-metadata.tlv.
        /// </summary>
        internal static string AggregationHashChain_Link_Invalid_SiblingHash_MetaHash_No_Metadata {
            get {
                return ResourceManager.GetString("AggregationHashChain_Link_Invalid_SiblingHash_MetaHash_No_Metadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/aggregation-hash-chain/aggregation-hash-chain-link-ok-missing-optionals.tlv.
        /// </summary>
        internal static string AggregationHashChain_Link_Ok_Missing_Optionals {
            get {
                return ResourceManager.GetString("AggregationHashChain_Link_Ok_Missing_Optionals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/aggregation-hash-chain/aggregation-hash-chain-metadata-invalid-extra-tag.tlv.
        /// </summary>
        internal static string AggregationHashChain_Metadata_Invalid_Extra_Tag {
            get {
                return ResourceManager.GetString("AggregationHashChain_Metadata_Invalid_Extra_Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/aggregation-hash-chain/aggregation-hash-chain-metadata-invalid-missing-client-id.tlv.
        /// </summary>
        internal static string AggregationHashChain_Metadata_Invalid_Missing_Client_id {
            get {
                return ResourceManager.GetString("AggregationHashChain_Metadata_Invalid_Missing_Client_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/aggregation-hash-chain/aggregation-hash-chain-metadata-invalid-multiple-client-id.tlv.
        /// </summary>
        internal static string AggregationHashChain_Metadata_Invalid_Multiple_Client_Id {
            get {
                return ResourceManager.GetString("AggregationHashChain_Metadata_Invalid_Multiple_Client_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/aggregation-hash-chain/aggregation-hash-chain-metadata-invalid-multiple-machine-id.tlv.
        /// </summary>
        internal static string AggregationHashChain_Metadata_Invalid_Multiple_Machine_Id {
            get {
                return ResourceManager.GetString("AggregationHashChain_Metadata_Invalid_Multiple_Machine_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/aggregation-hash-chain/aggregation-hash-chain-metadata-invalid-multiple-request-time.tlv.
        /// </summary>
        internal static string AggregationHashChain_Metadata_Invalid_Multiple_Request_Time {
            get {
                return ResourceManager.GetString("AggregationHashChain_Metadata_Invalid_Multiple_Request_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/aggregation-hash-chain/aggregation-hash-chain-metadata-invalid-multiple-sequence-nr.tlv.
        /// </summary>
        internal static string AggregationHashChain_Metadata_Invalid_Multiple_Sequence_Number {
            get {
                return ResourceManager.GetString("AggregationHashChain_Metadata_Invalid_Multiple_Sequence_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/aggregation-hash-chain/aggregation-hash-chain-metadata-ok-missing-optionals.tlv.
        /// </summary>
        internal static string AggregationHashChain_Metadata_Ok_Missing_Optionals {
            get {
                return ResourceManager.GetString("AggregationHashChain_Metadata_Ok_Missing_Optionals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/aggregation-hash-chain/aggregation-hash-chain-ok.tlv.
        /// </summary>
        internal static string AggregationHashChain_Ok {
            get {
                return ResourceManager.GetString("AggregationHashChain_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/aggregation-hash-chain/aggregation-hash-chain-ok-missing-optionals.tlv.
        /// </summary>
        internal static string AggregationHashChain_Ok_Missing_Optionals {
            get {
                return ResourceManager.GetString("AggregationHashChain_Ok_Missing_Optionals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/calendar-authentication-record/calendar-authentication-record-invalid-extra-tag.tlv.
        /// </summary>
        internal static string CalendarAuthenticationRecord_Invalid_Extra_Tag {
            get {
                return ResourceManager.GetString("CalendarAuthenticationRecord_Invalid_Extra_Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/calendar-authentication-record/calendar-authentication-record-invalid-missing-publicationdata.tlv.
        /// </summary>
        internal static string CalendarAuthenticationRecord_Invalid_Missing_Publication_Data {
            get {
                return ResourceManager.GetString("CalendarAuthenticationRecord_Invalid_Missing_Publication_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/calendar-authentication-record/calendar-authentication-record-invalid-missing-signaturedata.tlv.
        /// </summary>
        internal static string CalendarAuthenticationRecord_Invalid_Missing_Signature_Data {
            get {
                return ResourceManager.GetString("CalendarAuthenticationRecord_Invalid_Missing_Signature_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/calendar-authentication-record/calendar-authentication-record-invalid-multiple-publicationdata.tlv.
        /// </summary>
        internal static string CalendarAuthenticationRecord_Invalid_Multiple_Publication_Data {
            get {
                return ResourceManager.GetString("CalendarAuthenticationRecord_Invalid_Multiple_Publication_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/calendar-authentication-record/calendar-authentication-record-invalid-multiple-signaturedata.tlv.
        /// </summary>
        internal static string CalendarAuthenticationRecord_Invalid_Multiple_Signature_Data {
            get {
                return ResourceManager.GetString("CalendarAuthenticationRecord_Invalid_Multiple_Signature_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/calendar-authentication-record/calendar-authentication-record-invalid-type.tlv.
        /// </summary>
        internal static string CalendarAuthenticationRecord_Invalid_Type {
            get {
                return ResourceManager.GetString("CalendarAuthenticationRecord_Invalid_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/calendar-authentication-record/calendar-authentication-record-ok.tlv.
        /// </summary>
        internal static string CalendarAuthenticationRecord_Ok {
            get {
                return ResourceManager.GetString("CalendarAuthenticationRecord_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/calendar-hash-chain/calendar-hash-chain-invalid-extra-tag.tlv.
        /// </summary>
        internal static string CalendarHashChain_Invalid_Extra_Tag {
            get {
                return ResourceManager.GetString("CalendarHashChain_Invalid_Extra_Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/calendar-hash-chain/calendar-hash-chain-invalid-missing-input-hash.tlv.
        /// </summary>
        internal static string CalendarHashChain_Invalid_Missing_Input_Hash {
            get {
                return ResourceManager.GetString("CalendarHashChain_Invalid_Missing_Input_Hash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/calendar-hash-chain/calendar-hash-chain-invalid-missing-links.tlv.
        /// </summary>
        internal static string CalendarHashChain_Invalid_Missing_Links {
            get {
                return ResourceManager.GetString("CalendarHashChain_Invalid_Missing_Links", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/calendar-hash-chain/calendar-hash-chain-invalid-missing-publication-time.tlv.
        /// </summary>
        internal static string CalendarHashChain_Invalid_Missing_Publication_Time {
            get {
                return ResourceManager.GetString("CalendarHashChain_Invalid_Missing_Publication_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/calendar-hash-chain/calendar-hash-chain-invalid-multiple-aggregation-time.tlv.
        /// </summary>
        internal static string CalendarHashChain_Invalid_Multiple_Aggregation_Time {
            get {
                return ResourceManager.GetString("CalendarHashChain_Invalid_Multiple_Aggregation_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/calendar-hash-chain/calendar-hash-chain-invalid-multiple-input-hash.tlv.
        /// </summary>
        internal static string CalendarHashChain_Invalid_Multiple_Input_Hash {
            get {
                return ResourceManager.GetString("CalendarHashChain_Invalid_Multiple_Input_Hash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/calendar-hash-chain/calendar-hash-chain-invalid-multiple-publication-time.tlv.
        /// </summary>
        internal static string CalendarHashChain_Invalid_Multiple_Publication_Time {
            get {
                return ResourceManager.GetString("CalendarHashChain_Invalid_Multiple_Publication_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/calendar-hash-chain/calendar-hash-chain-invalid-type.tlv.
        /// </summary>
        internal static string CalendarHashChain_Invalid_Type {
            get {
                return ResourceManager.GetString("CalendarHashChain_Invalid_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/calendar-hash-chain/calendar-hash-chain-ok.tlv.
        /// </summary>
        internal static string CalendarHashChain_Ok {
            get {
                return ResourceManager.GetString("CalendarHashChain_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/calendar-hash-chain/calendar-hash-chain-ok-missing-optionals.tlv.
        /// </summary>
        internal static string CalendarHashChain_Ok_Missing_Optionals {
            get {
                return ResourceManager.GetString("CalendarHashChain_Ok_Missing_Optionals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/testdata.txt.
        /// </summary>
        internal static string DataHasher_TestFile {
            get {
                return ResourceManager.GetString("DataHasher_TestFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LongString1ReallyLongString2EvenLongerString3.
        /// </summary>
        internal static string DataHasher_TestString {
            get {
                return ResourceManager.GetString("DataHasher_TestString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/ksi-signature-do/ksi-signature-invalid-aggregation-chain-aggregation-time-mismatch.tlv.
        /// </summary>
        internal static string KsiSignatureDo_Invalid_Aggregation_Chain_Aggregation_Time_Mismatch {
            get {
                return ResourceManager.GetString("KsiSignatureDo_Invalid_Aggregation_Chain_Aggregation_Time_Mismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/ksi-signature-do/ksi-signature-invalid-aggregation-chain-index-mismatch.tlv.
        /// </summary>
        internal static string KsiSignatureDo_Invalid_Aggregation_Chain_Index_Mismatch {
            get {
                return ResourceManager.GetString("KsiSignatureDo_Invalid_Aggregation_Chain_Index_Mismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/ksi-signature-do/ksi-signature-invalid-aggregation-chain-input-hash.tlv.
        /// </summary>
        internal static string KsiSignatureDo_Invalid_Aggregation_Chain_Input_Hash {
            get {
                return ResourceManager.GetString("KsiSignatureDo_Invalid_Aggregation_Chain_Input_Hash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/ksi-signature-do/ksi-signature-invalid-calendar-authentication-record-invalid-publication-hash.tlv.
        /// </summary>
        internal static string KsiSignatureDo_Invalid_Calendar_Authentication_Record_Invalid_Publication_Hash {
            get {
                return ResourceManager.GetString("KsiSignatureDo_Invalid_Calendar_Authentication_Record_Invalid_Publication_Hash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/ksi-signature-do/ksi-signature-invalid-calendar-authentication-record-invalid-publication-time.tlv.
        /// </summary>
        internal static string KsiSignatureDo_Invalid_Calendar_Authentication_Record_Invalid_Publication_Time {
            get {
                return ResourceManager.GetString("KsiSignatureDo_Invalid_Calendar_Authentication_Record_Invalid_Publication_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/ksi-signature-do/ksi-signature-invalid-calendar-authentication-record-invalid-signature.tlv.
        /// </summary>
        internal static string KsiSignatureDo_Invalid_Calendar_Authentication_Record_Invalid_Signature {
            get {
                return ResourceManager.GetString("KsiSignatureDo_Invalid_Calendar_Authentication_Record_Invalid_Signature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/ksi-signature-do/ksi-signature-invalid-calendar-hash-chain-input-hash.tlv.
        /// </summary>
        internal static string KsiSignatureDo_Invalid_Calendar_Chain_Input_Hash {
            get {
                return ResourceManager.GetString("KsiSignatureDo_Invalid_Calendar_Chain_Input_Hash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/ksi-signature-do/ksi-signature-invalid-calendar-hash-chain-publication-time.tlv.
        /// </summary>
        internal static string KsiSignatureDo_Invalid_Calendar_Chain_Publication_Time {
            get {
                return ResourceManager.GetString("KsiSignatureDo_Invalid_Calendar_Chain_Publication_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/ksi-signature-do/ksi-signature-invalid-contain-both-publication-record-and-calendar-authentication-record.tlv.
        /// </summary>
        internal static string KsiSignatureDo_Invalid_Contain_Publication_Record_And_Calendar_Authentication_Record {
            get {
                return ResourceManager.GetString("KsiSignatureDo_Invalid_Contain_Publication_Record_And_Calendar_Authentication_Rec" +
                        "ord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/ksi-signature-do/ksi-signature-invalid-extra-tag.tlv.
        /// </summary>
        internal static string KsiSignatureDo_Invalid_Extra_Tag {
            get {
                return ResourceManager.GetString("KsiSignatureDo_Invalid_Extra_Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/ksi-signature-do/ksi-signature-invalid-hash-algorithm.tlv.
        /// </summary>
        internal static string KsiSignatureDo_Invalid_Hash_Algorithm {
            get {
                return ResourceManager.GetString("KsiSignatureDo_Invalid_Hash_Algorithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/ksi-signature-do/ksi-signature-invalid-missing-aggregation-hash-chains.tlv.
        /// </summary>
        internal static string KsiSignatureDo_Invalid_Missing_Aggregation_Hash_Chain {
            get {
                return ResourceManager.GetString("KsiSignatureDo_Invalid_Missing_Aggregation_Hash_Chain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/ksi-signature-do/ksi-signature-invalid-missing-calendar-auth-record.tlv.
        /// </summary>
        internal static string KsiSignatureDo_Invalid_Missing_Calendar_Authentication_Record {
            get {
                return ResourceManager.GetString("KsiSignatureDo_Invalid_Missing_Calendar_Authentication_Record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/ksi-signature-do/ksi-signature-Invalid-Missing-calendar-hash-chain.tlv.
        /// </summary>
        internal static string KsiSignatureDo_Invalid_Missing_Calendar_Hash_Chain {
            get {
                return ResourceManager.GetString("KsiSignatureDo_Invalid_Missing_Calendar_Hash_Chain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/ksi-signature-do/ksi-signature-invalid-multiple-calendar-authentication-records.tlv.
        /// </summary>
        internal static string KsiSignatureDo_Invalid_Multiple_Calendar_Authentication_Records {
            get {
                return ResourceManager.GetString("KsiSignatureDo_Invalid_Multiple_Calendar_Authentication_Records", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/ksi-signature-do/ksi-signature-invalid-multiple-calendar-hash-chains.tlv.
        /// </summary>
        internal static string KsiSignatureDo_Invalid_Multiple_Calendar_Hash_Chains {
            get {
                return ResourceManager.GetString("KsiSignatureDo_Invalid_Multiple_Calendar_Hash_Chains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/ksi-signature-do/ksi-signature-invalid-multiple-publication-records.tlv.
        /// </summary>
        internal static string KsiSignatureDo_Invalid_Multiple_Publication_Records {
            get {
                return ResourceManager.GetString("KsiSignatureDo_Invalid_Multiple_Publication_Records", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/ksi-signature-do/ksi-signature-invalid-multiple-rfc3161-records.tlv.
        /// </summary>
        internal static string KsiSignatureDo_Invalid_Multiple_Rfc_3161_Records {
            get {
                return ResourceManager.GetString("KsiSignatureDo_Invalid_Multiple_Rfc_3161_Records", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/ksi-signature-do/ksi-signature-invalid-type.tlv.
        /// </summary>
        internal static string KsiSignatureDo_Invalid_Type {
            get {
                return ResourceManager.GetString("KsiSignatureDo_Invalid_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/ksi-signature-do/ksi-signature-invalid-aggregation-root-hash.tlv.
        /// </summary>
        internal static string KsiSignatureDo_Invalid_With_Invalid_Aggregation_Root_Hash {
            get {
                return ResourceManager.GetString("KsiSignatureDo_Invalid_With_Invalid_Aggregation_Root_Hash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/ksi-signature-do/ksi-signature-invalid-with-invalid-publication-record.tlv.
        /// </summary>
        internal static string KsiSignatureDo_Invalid_With_Invalid_Publication_Record {
            get {
                return ResourceManager.GetString("KsiSignatureDo_Invalid_With_Invalid_Publication_Record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/ksi-signature-do/legacy-ksi-signature-ok.tlv.
        /// </summary>
        internal static string KsiSignatureDo_Legacy_Ok {
            get {
                return ResourceManager.GetString("KsiSignatureDo_Legacy_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/ksi-signature-do/legacy-ksi-signature-ok-with-publication-record.tlv.
        /// </summary>
        internal static string KsiSignatureDo_Legacy_Ok_With_Publication_Record {
            get {
                return ResourceManager.GetString("KsiSignatureDo_Legacy_Ok_With_Publication_Record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/ksi-signature-do/ksi-signature-ok.tlv.
        /// </summary>
        internal static string KsiSignatureDo_Ok {
            get {
                return ResourceManager.GetString("KsiSignatureDo_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/ksi-signature-do/ksi-signature-ok-extended.tlv.
        /// </summary>
        internal static string KsiSignatureDo_Ok_Extended {
            get {
                return ResourceManager.GetString("KsiSignatureDo_Ok_Extended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/ksi-signature-do/ksi-signature-ok-identity.tlv.
        /// </summary>
        internal static string KsiSignatureDo_Ok_Identity {
            get {
                return ResourceManager.GetString("KsiSignatureDo_Ok_Identity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/ksi-signature-do/ksi-signature-ok-Missing-publication-record-and-calendar-authentication-record.tlv.
        /// </summary>
        internal static string KsiSignatureDo_Ok_Missing_Publication_Record_And_Calendar_Authentication_Record {
            get {
                return ResourceManager.GetString("KsiSignatureDo_Ok_Missing_Publication_Record_And_Calendar_Authentication_Record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/ksi-signature-do/ksi-signature-ok-new.tlv.
        /// </summary>
        internal static string KsiSignatureDo_Ok_New {
            get {
                return ResourceManager.GetString("KsiSignatureDo_Ok_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/ksi-signature-do/ksi-signature-ok-with-mixed-aggregation-chains.tlv.
        /// </summary>
        internal static string KsiSignatureDo_Ok_With_Mixed_Aggregation_Chains {
            get {
                return ResourceManager.GetString("KsiSignatureDo_Ok_With_Mixed_Aggregation_Chains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/ksi-signature-do/ksi-signature-ok-with-publication-record.tlv.
        /// </summary>
        internal static string KsiSignatureDo_Ok_With_Publication_Record {
            get {
                return ResourceManager.GetString("KsiSignatureDo_Ok_With_Publication_Record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/rfc3161-record/rfc3161-record-invalid-extra-tag.tlv.
        /// </summary>
        internal static string Rfc3161Record_Invalid_Extra_Tag {
            get {
                return ResourceManager.GetString("Rfc3161Record_Invalid_Extra_Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/rfc3161-record/rfc3161-record-invalid-missing-aggregation-time.tlv.
        /// </summary>
        internal static string Rfc3161Record_Invalid_Missing_Aggregation_Time {
            get {
                return ResourceManager.GetString("Rfc3161Record_Invalid_Missing_Aggregation_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/rfc3161-record/rfc3161-record-invalid-missing-chain-index.tlv.
        /// </summary>
        internal static string Rfc3161Record_Invalid_Missing_Chain_Index {
            get {
                return ResourceManager.GetString("Rfc3161Record_Invalid_Missing_Chain_Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/rfc3161-record/rfc3161-record-invalid-missing-input-hash.tlv.
        /// </summary>
        internal static string Rfc3161Record_Invalid_Missing_Input_Hash {
            get {
                return ResourceManager.GetString("Rfc3161Record_Invalid_Missing_Input_Hash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/rfc3161-record/rfc3161-record-invalid-missing-signed-attributes-algorithm.tlv.
        /// </summary>
        internal static string Rfc3161Record_Invalid_Missing_Signed_Attributes_Algorithm {
            get {
                return ResourceManager.GetString("Rfc3161Record_Invalid_Missing_Signed_Attributes_Algorithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/rfc3161-record/rfc3161-record-invalid-missing-signed-attributes-prefix.tlv.
        /// </summary>
        internal static string Rfc3161Record_Invalid_Missing_Signed_Attributes_Prefix {
            get {
                return ResourceManager.GetString("Rfc3161Record_Invalid_Missing_Signed_Attributes_Prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/rfc3161-record/rfc3161-record-invalid-missing-signed-attributes-suffix.tlv.
        /// </summary>
        internal static string Rfc3161Record_Invalid_Missing_Signed_Attributes_Suffix {
            get {
                return ResourceManager.GetString("Rfc3161Record_Invalid_Missing_Signed_Attributes_Suffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/rfc3161-record/rfc3161-record-invalid-missing-tstinfo-algorithm.tlv.
        /// </summary>
        internal static string Rfc3161Record_Invalid_Missing_TstInfo_Algorithm {
            get {
                return ResourceManager.GetString("Rfc3161Record_Invalid_Missing_TstInfo_Algorithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/rfc3161-record/rfc3161-record-invalid-missing-tstinfo-prefix.tlv.
        /// </summary>
        internal static string Rfc3161Record_Invalid_Missing_TstInfo_Prefix {
            get {
                return ResourceManager.GetString("Rfc3161Record_Invalid_Missing_TstInfo_Prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/rfc3161-record/rfc3161-record-invalid-missing-tstinfo-suffix.tlv.
        /// </summary>
        internal static string Rfc3161Record_Invalid_Missing_TstInfo_Suffix {
            get {
                return ResourceManager.GetString("Rfc3161Record_Invalid_Missing_TstInfo_Suffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/rfc3161-record/rfc3161-record-invalid-multiple-aggregation-time.tlv.
        /// </summary>
        internal static string Rfc3161Record_Invalid_Multiple_Aggregation_Time {
            get {
                return ResourceManager.GetString("Rfc3161Record_Invalid_Multiple_Aggregation_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/rfc3161-record/rfc3161-record-invalid-multiple-input-hash.tlv.
        /// </summary>
        internal static string Rfc3161Record_Invalid_Multiple_Input_Hash {
            get {
                return ResourceManager.GetString("Rfc3161Record_Invalid_Multiple_Input_Hash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/rfc3161-record/rfc3161-record-invalid-multiple-signed-attributes-algorithm.tlv.
        /// </summary>
        internal static string Rfc3161Record_Invalid_Multiple_Signed_Attributes_Algorithm {
            get {
                return ResourceManager.GetString("Rfc3161Record_Invalid_Multiple_Signed_Attributes_Algorithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/rfc3161-record/rfc3161-record-invalid-multiple-signed-attributes-prefix.tlv.
        /// </summary>
        internal static string Rfc3161Record_Invalid_Multiple_Signed_Attributes_Prefix {
            get {
                return ResourceManager.GetString("Rfc3161Record_Invalid_Multiple_Signed_Attributes_Prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/rfc3161-record/rfc3161-record-invalid-multiple-signed-attributes-suffix.tlv.
        /// </summary>
        internal static string Rfc3161Record_Invalid_Multiple_Signed_Attributes_Suffix {
            get {
                return ResourceManager.GetString("Rfc3161Record_Invalid_Multiple_Signed_Attributes_Suffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/rfc3161-record/rfc3161-record-invalid-multiple-tstinfo-algorithm.tlv.
        /// </summary>
        internal static string Rfc3161Record_Invalid_Multiple_TstInfo_Algorithm {
            get {
                return ResourceManager.GetString("Rfc3161Record_Invalid_Multiple_TstInfo_Algorithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/rfc3161-record/rfc3161-record-invalid-multiple-tstinfo-prefix.tlv.
        /// </summary>
        internal static string Rfc3161Record_Invalid_Multiple_TstInfo_Prefix {
            get {
                return ResourceManager.GetString("Rfc3161Record_Invalid_Multiple_TstInfo_Prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/rfc3161-record/rfc3161-record-invalid-multiple-tstinfo-suffix.tlv.
        /// </summary>
        internal static string Rfc3161Record_Invalid_Multiple_TstInfo_Suffix {
            get {
                return ResourceManager.GetString("Rfc3161Record_Invalid_Multiple_TstInfo_Suffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/rfc3161-record/rfc3161-record-invalid-type.tlv.
        /// </summary>
        internal static string Rfc3161Record_Invalid_Type {
            get {
                return ResourceManager.GetString("Rfc3161Record_Invalid_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/rfc3161-record/rfc3161-record-ok.tlv.
        /// </summary>
        internal static string Rfc3161Record_Ok {
            get {
                return ResourceManager.GetString("Rfc3161Record_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/signaturedata/signature-data-invalid-certificate-id-missing.tlv.
        /// </summary>
        internal static string SignatureData_Invalid_Certificate_Id_Missing {
            get {
                return ResourceManager.GetString("SignatureData_Invalid_Certificate_Id_Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/signaturedata/signature-data-invalid-extra-tag.tlv.
        /// </summary>
        internal static string SignatureData_Invalid_Extra_Tag {
            get {
                return ResourceManager.GetString("SignatureData_Invalid_Extra_Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/signaturedata/signature-data-invalid-multiple-certificate-id.tlv.
        /// </summary>
        internal static string SignatureData_Invalid_Multiple_Certificate_Id {
            get {
                return ResourceManager.GetString("SignatureData_Invalid_Multiple_Certificate_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/signaturedata/signature-data-invalid-multiple-certificate-rep-uri.tlv.
        /// </summary>
        internal static string SignatureData_Invalid_Multiple_Certificate_Rep_Uri {
            get {
                return ResourceManager.GetString("SignatureData_Invalid_Multiple_Certificate_Rep_Uri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/signaturedata/signature-data-invalid-multiple-type.tlv.
        /// </summary>
        internal static string SignatureData_Invalid_Multiple_Signature_Type {
            get {
                return ResourceManager.GetString("SignatureData_Invalid_Multiple_Signature_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/signaturedata/signature-data-invalid-multiple-value.tlv.
        /// </summary>
        internal static string SignatureData_Invalid_Multiple_Signature_Value {
            get {
                return ResourceManager.GetString("SignatureData_Invalid_Multiple_Signature_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/signaturedata/signature-data-invalid-type-missing.tlv.
        /// </summary>
        internal static string SignatureData_Invalid_Signature_Type_Missing {
            get {
                return ResourceManager.GetString("SignatureData_Invalid_Signature_Type_Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/signaturedata/signature-data-invalid-value-missing.tlv.
        /// </summary>
        internal static string SignatureData_Invalid_Signature_Value_Missing {
            get {
                return ResourceManager.GetString("SignatureData_Invalid_Signature_Value_Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/signaturedata/signature-data-invalid-type.tlv.
        /// </summary>
        internal static string SignatureData_Invalid_Wrong_Type {
            get {
                return ResourceManager.GetString("SignatureData_Invalid_Wrong_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/signaturedata/signature-data-ok.tlv.
        /// </summary>
        internal static string SignatureData_Ok {
            get {
                return ResourceManager.GetString("SignatureData_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/signaturedata/signature-data-ok-no-uri.tlv.
        /// </summary>
        internal static string SignatureData_Ok_No_Uri {
            get {
                return ResourceManager.GetString("SignatureData_Ok_No_Uri", resourceCulture);
            }
        }
    }
}
