//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Guardtime.KSI.Test.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Guardtime.KSI.Test.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/aggregation-authentication-record/aggregation-authentication-record-invalid-extra-tag.tlv.
        /// </summary>
        internal static string AggregationAuthenticationRecord_Invalid_Extra_Tag {
            get {
                return ResourceManager.GetString("AggregationAuthenticationRecord_Invalid_Extra_Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/aggregation-authentication-record/aggregation-authentication-record-invalid-missing-aggregation-time.tlv.
        /// </summary>
        internal static string AggregationAuthenticationRecord_Invalid_Missing_Aggregation_Time {
            get {
                return ResourceManager.GetString("AggregationAuthenticationRecord_Invalid_Missing_Aggregation_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/aggregation-authentication-record/aggregation-authentication-record-invalid-missing-chain-index.tlv.
        /// </summary>
        internal static string AggregationAuthenticationRecord_Invalid_Missing_Chain_Index {
            get {
                return ResourceManager.GetString("AggregationAuthenticationRecord_Invalid_Missing_Chain_Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/aggregation-authentication-record/aggregation-authentication-record-invalid-missing-input-hash.tlv.
        /// </summary>
        internal static string AggregationAuthenticationRecord_Invalid_Missing_Input_Hash {
            get {
                return ResourceManager.GetString("AggregationAuthenticationRecord_Invalid_Missing_Input_Hash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/aggregation-authentication-record/aggregation-authentication-record-invalid-missing-signature-data.tlv.
        /// </summary>
        internal static string AggregationAuthenticationRecord_Invalid_Missing_Signature_Data {
            get {
                return ResourceManager.GetString("AggregationAuthenticationRecord_Invalid_Missing_Signature_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/aggregation-authentication-record/aggregation-authentication-record-invalid-multiple-aggregation-time.tlv.
        /// </summary>
        internal static string AggregationAuthenticationRecord_Invalid_Multiple_Aggregation_Time {
            get {
                return ResourceManager.GetString("AggregationAuthenticationRecord_Invalid_Multiple_Aggregation_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/aggregation-authentication-record/aggregation-authentication-record-invalid-multiple-input-hash.tlv.
        /// </summary>
        internal static string AggregationAuthenticationRecord_Invalid_Multiple_Input_Hash {
            get {
                return ResourceManager.GetString("AggregationAuthenticationRecord_Invalid_Multiple_Input_Hash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/aggregation-authentication-record/aggregation-authentication-record-invalid-multiple-signature-data.tlv.
        /// </summary>
        internal static string AggregationAuthenticationRecord_Invalid_Multiple_Signature_Data {
            get {
                return ResourceManager.GetString("AggregationAuthenticationRecord_Invalid_Multiple_Signature_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/aggregation-authentication-record/aggregation-authentication-record-invalid-type.tlv.
        /// </summary>
        internal static string AggregationAuthenticationRecord_Invalid_Type {
            get {
                return ResourceManager.GetString("AggregationAuthenticationRecord_Invalid_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/aggregation-authentication-record/aggregation-authentication-record-ok.tlv.
        /// </summary>
        internal static string AggregationAuthenticationRecord_Ok {
            get {
                return ResourceManager.GetString("AggregationAuthenticationRecord_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/aggregation-hash-chain/aggregation-hash-chain-invalid-extra-tag.tlv.
        /// </summary>
        internal static string AggregationHashChain_Invalid_Extra_Tag {
            get {
                return ResourceManager.GetString("AggregationHashChain_Invalid_Extra_Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/aggregation-hash-chain/aggregation-hash-chain-invalid-missing-aggregation-algorithm.tlv.
        /// </summary>
        internal static string AggregationHashChain_Invalid_Missing_Aggregation_Algorithm {
            get {
                return ResourceManager.GetString("AggregationHashChain_Invalid_Missing_Aggregation_Algorithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/aggregation-hash-chain/aggregation-hash-chain-invalid-missing-aggregation-time.tlv.
        /// </summary>
        internal static string AggregationHashChain_Invalid_Missing_Aggregation_Time {
            get {
                return ResourceManager.GetString("AggregationHashChain_Invalid_Missing_Aggregation_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/aggregation-hash-chain/aggregation-hash-chain-invalid-missing-chain-index.tlv.
        /// </summary>
        internal static string AggregationHashChain_Invalid_Missing_Chain_Index {
            get {
                return ResourceManager.GetString("AggregationHashChain_Invalid_Missing_Chain_Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/aggregation-hash-chain/aggregation-hash-chain-invalid-missing-input-hash.tlv.
        /// </summary>
        internal static string AggregationHashChain_Invalid_Missing_Input_Hash {
            get {
                return ResourceManager.GetString("AggregationHashChain_Invalid_Missing_Input_Hash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/aggregation-hash-chain/aggregation-hash-chain-invalid-missing-links.tlv.
        /// </summary>
        internal static string AggregationHashChain_Invalid_Missing_Links {
            get {
                return ResourceManager.GetString("AggregationHashChain_Invalid_Missing_Links", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/aggregation-hash-chain/aggregation-hash-chain-invalid-multiple-aggregation-algorithm.tlv.
        /// </summary>
        internal static string AggregationHashChain_Invalid_Multiple_Aggregation_Algorithm {
            get {
                return ResourceManager.GetString("AggregationHashChain_Invalid_Multiple_Aggregation_Algorithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/aggregation-hash-chain/aggregation-hash-chain-invalid-multiple-aggregation-time.tlv.
        /// </summary>
        internal static string AggregationHashChain_Invalid_Multiple_Aggregation_Time {
            get {
                return ResourceManager.GetString("AggregationHashChain_Invalid_Multiple_Aggregation_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/aggregation-hash-chain/aggregation-hash-chain-invalid-multiple-input-data.tlv.
        /// </summary>
        internal static string AggregationHashChain_Invalid_Multiple_Input_Data {
            get {
                return ResourceManager.GetString("AggregationHashChain_Invalid_Multiple_Input_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/aggregation-hash-chain/aggregation-hash-chain-invalid-multiple-input-hash.tlv.
        /// </summary>
        internal static string AggregationHashChain_Invalid_Multiple_Input_Hash {
            get {
                return ResourceManager.GetString("AggregationHashChain_Invalid_Multiple_Input_Hash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/aggregation-hash-chain/aggregation-hash-chain-invalid-type.tlv.
        /// </summary>
        internal static string AggregationHashChain_Invalid_Type {
            get {
                return ResourceManager.GetString("AggregationHashChain_Invalid_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/aggregation-hash-chain/aggregation-hash-chain-link-invalid-all-tags-exist.tlv.
        /// </summary>
        internal static string AggregationHashChain_Link_Invalid_All_Tags_Defined {
            get {
                return ResourceManager.GetString("AggregationHashChain_Link_Invalid_All_Tags_Defined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/aggregation-hash-chain/aggregation-hash-chain-link-invalid-empty.tlv.
        /// </summary>
        internal static string AggregationHashChain_Link_Invalid_Empty {
            get {
                return ResourceManager.GetString("AggregationHashChain_Link_Invalid_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/aggregation-hash-chain/aggregation-hash-chain-link-invalid-extra-tag.tlv.
        /// </summary>
        internal static string AggregationHashChain_Link_Invalid_Extra_Tag {
            get {
                return ResourceManager.GetString("AggregationHashChain_Link_Invalid_Extra_Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/aggregation-hash-chain/aggregation-hash-chain-link-invalid-metadata-metahash-no-siblinghash.tlv.
        /// </summary>
        internal static string AggregationHashChain_Link_Invalid_Metadata_Metahash_No_SiblingHash {
            get {
                return ResourceManager.GetString("AggregationHashChain_Link_Invalid_Metadata_Metahash_No_SiblingHash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/aggregation-hash-chain/aggregation-hash-chain-link-invalid-multiple-levelcorrection.tlv.
        /// </summary>
        internal static string AggregationHashChain_Link_Invalid_Multiple_LevelCorrection {
            get {
                return ResourceManager.GetString("AggregationHashChain_Link_Invalid_Multiple_LevelCorrection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/aggregation-hash-chain/aggregation-hash-chain-link-invalid-multiple-metadata.tlv.
        /// </summary>
        internal static string AggregationHashChain_Link_Invalid_Multiple_Metadata {
            get {
                return ResourceManager.GetString("AggregationHashChain_Link_Invalid_Multiple_Metadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/aggregation-hash-chain/aggregation-hash-chain-link-invalid-multiple-metahash.tlv.
        /// </summary>
        internal static string AggregationHashChain_Link_Invalid_Multiple_Metahash {
            get {
                return ResourceManager.GetString("AggregationHashChain_Link_Invalid_Multiple_Metahash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/aggregation-hash-chain/aggregation-hash-chain-link-invalid-multiple-siblinghash.tlv.
        /// </summary>
        internal static string AggregationHashChain_Link_Invalid_Multiple_Siblinghash {
            get {
                return ResourceManager.GetString("AggregationHashChain_Link_Invalid_Multiple_Siblinghash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/aggregation-hash-chain/aggregation-hash-chain-link-invalid-sibling-metadata-no-metahash.tlv.
        /// </summary>
        internal static string AggregationHashChain_Link_Invalid_SiblingHash_Metadata_No_MetaHash {
            get {
                return ResourceManager.GetString("AggregationHashChain_Link_Invalid_SiblingHash_Metadata_No_MetaHash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/aggregation-hash-chain/aggregation-hash-chain-link-invalid-sibling-metahash-and-no-metadata.tlv.
        /// </summary>
        internal static string AggregationHashChain_Link_Invalid_SiblingHash_MetaHash_No_Metadata {
            get {
                return ResourceManager.GetString("AggregationHashChain_Link_Invalid_SiblingHash_MetaHash_No_Metadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/aggregation-hash-chain/aggregation-hash-chain-link-ok-missing-optionals.tlv.
        /// </summary>
        internal static string AggregationHashChain_Link_Ok_Missing_Optionals {
            get {
                return ResourceManager.GetString("AggregationHashChain_Link_Ok_Missing_Optionals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/aggregation-hash-chain/aggregation-hash-chain-metadata-invalid-extra-tag.tlv.
        /// </summary>
        internal static string AggregationHashChain_Metadata_Invalid_Extra_Tag {
            get {
                return ResourceManager.GetString("AggregationHashChain_Metadata_Invalid_Extra_Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/aggregation-hash-chain/aggregation-hash-chain-metadata-invalid-missing-client-id.tlv.
        /// </summary>
        internal static string AggregationHashChain_Metadata_Invalid_Missing_Client_id {
            get {
                return ResourceManager.GetString("AggregationHashChain_Metadata_Invalid_Missing_Client_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/aggregation-hash-chain/aggregation-hash-chain-metadata-invalid-multiple-client-id.tlv.
        /// </summary>
        internal static string AggregationHashChain_Metadata_Invalid_Multiple_Client_Id {
            get {
                return ResourceManager.GetString("AggregationHashChain_Metadata_Invalid_Multiple_Client_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/aggregation-hash-chain/aggregation-hash-chain-metadata-invalid-multiple-machine-id.tlv.
        /// </summary>
        internal static string AggregationHashChain_Metadata_Invalid_Multiple_Machine_Id {
            get {
                return ResourceManager.GetString("AggregationHashChain_Metadata_Invalid_Multiple_Machine_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/aggregation-hash-chain/aggregation-hash-chain-metadata-invalid-multiple-request-time.tlv.
        /// </summary>
        internal static string AggregationHashChain_Metadata_Invalid_Multiple_Request_Time {
            get {
                return ResourceManager.GetString("AggregationHashChain_Metadata_Invalid_Multiple_Request_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/aggregation-hash-chain/aggregation-hash-chain-metadata-invalid-multiple-sequence-nr.tlv.
        /// </summary>
        internal static string AggregationHashChain_Metadata_Invalid_Multiple_Sequence_Number {
            get {
                return ResourceManager.GetString("AggregationHashChain_Metadata_Invalid_Multiple_Sequence_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/aggregation-hash-chain/aggregation-hash-chain-metadata-ok-missing-optionals.tlv.
        /// </summary>
        internal static string AggregationHashChain_Metadata_Ok_Missing_Optionals {
            get {
                return ResourceManager.GetString("AggregationHashChain_Metadata_Ok_Missing_Optionals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/aggregation-hash-chain/aggregation-hash-chain-ok.tlv.
        /// </summary>
        internal static string AggregationHashChain_Ok {
            get {
                return ResourceManager.GetString("AggregationHashChain_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/aggregation-hash-chain/aggregation-hash-chain-ok-missing-optionals.tlv.
        /// </summary>
        internal static string AggregationHashChain_Ok_Missing_Optionals {
            get {
                return ResourceManager.GetString("AggregationHashChain_Ok_Missing_Optionals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/aggregation-hash-chain/MetadataPadding/TestAggregationHashChainMetadataInvalidPaddingFail.ksig.
        /// </summary>
        internal static string AggregationHashChainMetadataInvalidPaddingFail {
            get {
                return ResourceManager.GetString("AggregationHashChainMetadataInvalidPaddingFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/aggregation-hash-chain/MetadataPadding/TestAggregationHashChainMetadataPaddingNotFirstFail.ksig.
        /// </summary>
        internal static string AggregationHashChainMetadataPaddingNotFirstFail {
            get {
                return ResourceManager.GetString("AggregationHashChainMetadataPaddingNotFirstFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/aggregation-hash-chain/MetadataPadding/TestAggregationHashChainMetadataPaddingNotForwardFail.ksig.
        /// </summary>
        internal static string AggregationHashChainMetadataPaddingNotForwardFail {
            get {
                return ResourceManager.GetString("AggregationHashChainMetadataPaddingNotForwardFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/aggregation-hash-chain/MetadataPadding/TestAggregationHashChainMetadataPaddingNotForwardNotNonCriticalFail.ksig.
        /// </summary>
        internal static string AggregationHashChainMetadataPaddingNotForwardNotNonCriticalFail {
            get {
                return ResourceManager.GetString("AggregationHashChainMetadataPaddingNotForwardNotNonCriticalFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/aggregation-hash-chain/MetadataPadding/TestAggregationHashChainMetadataPaddingNotNonCriticalFail.ksig.
        /// </summary>
        internal static string AggregationHashChainMetadataPaddingNotNonCriticalFail {
            get {
                return ResourceManager.GetString("AggregationHashChainMetadataPaddingNotNonCriticalFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/aggregation-hash-chain/MetadataPadding/TestAggregationHashChainMetadataPaddingNotTlv8Fail.ksig.
        /// </summary>
        internal static string AggregationHashChainMetadataPaddingNotTlv8Fail {
            get {
                return ResourceManager.GetString("AggregationHashChainMetadataPaddingNotTlv8Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/aggregation-hash-chain/MetadataPadding/TestAggregationHashChainMetadataUnknownPaddingValue1Fail.ksig.
        /// </summary>
        internal static string AggregationHashChainMetadataUnknownPaddingValue1Fail {
            get {
                return ResourceManager.GetString("AggregationHashChainMetadataUnknownPaddingValue1Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/aggregation-hash-chain/MetadataPadding/TestAggregationHashChainMetadataUnknownPaddingValue2Fail.ksig.
        /// </summary>
        internal static string AggregationHashChainMetadataUnknownPaddingValue2Fail {
            get {
                return ResourceManager.GetString("AggregationHashChainMetadataUnknownPaddingValue2Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/aggregation-hash-chain/MetadataPadding/TestAggregationHashChainMetadataUnknownPaddingValue3Fail.ksig.
        /// </summary>
        internal static string AggregationHashChainMetadataUnknownPaddingValue3Fail {
            get {
                return ResourceManager.GetString("AggregationHashChainMetadataUnknownPaddingValue3Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/aggregation-hash-chain/MetadataPadding/TestAggregationHashChainMetadataWithoutPadding.ksig.
        /// </summary>
        internal static string AggregationHashChainMetadataWithoutPadding {
            get {
                return ResourceManager.GetString("AggregationHashChainMetadataWithoutPadding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/aggregation-hash-chain/MetadataPadding/TestAggregationHashChainMetadataWithoutPaddingFail.ksig.
        /// </summary>
        internal static string AggregationHashChainMetadataWithoutPaddingFail {
            get {
                return ResourceManager.GetString("AggregationHashChainMetadataWithoutPaddingFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/aggregation-hash-chain/MetadataPadding/TestAggregationHashChainMetadataWithPadding1.ksig.
        /// </summary>
        internal static string AggregationHashChainMetadataWithPadding1 {
            get {
                return ResourceManager.GetString("AggregationHashChainMetadataWithPadding1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/aggregation-hash-chain/MetadataPadding/TestAggregationHashChainMetadataWithPadding2.ksig.
        /// </summary>
        internal static string AggregationHashChainMetadataWithPadding2 {
            get {
                return ResourceManager.GetString("AggregationHashChainMetadataWithPadding2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/calendar-authentication-record/calendar-authentication-record-invalid-extra-tag.tlv.
        /// </summary>
        internal static string CalendarAuthenticationRecord_Invalid_Extra_Tag {
            get {
                return ResourceManager.GetString("CalendarAuthenticationRecord_Invalid_Extra_Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/calendar-authentication-record/calendar-authentication-record-invalid-missing-publicationdata.tlv.
        /// </summary>
        internal static string CalendarAuthenticationRecord_Invalid_Missing_Publication_Data {
            get {
                return ResourceManager.GetString("CalendarAuthenticationRecord_Invalid_Missing_Publication_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/calendar-authentication-record/calendar-authentication-record-invalid-missing-signaturedata.tlv.
        /// </summary>
        internal static string CalendarAuthenticationRecord_Invalid_Missing_Signature_Data {
            get {
                return ResourceManager.GetString("CalendarAuthenticationRecord_Invalid_Missing_Signature_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/calendar-authentication-record/calendar-authentication-record-invalid-multiple-publicationdata.tlv.
        /// </summary>
        internal static string CalendarAuthenticationRecord_Invalid_Multiple_Publication_Data {
            get {
                return ResourceManager.GetString("CalendarAuthenticationRecord_Invalid_Multiple_Publication_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/calendar-authentication-record/calendar-authentication-record-invalid-multiple-signaturedata.tlv.
        /// </summary>
        internal static string CalendarAuthenticationRecord_Invalid_Multiple_Signature_Data {
            get {
                return ResourceManager.GetString("CalendarAuthenticationRecord_Invalid_Multiple_Signature_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/calendar-authentication-record/calendar-authentication-record-invalid-type.tlv.
        /// </summary>
        internal static string CalendarAuthenticationRecord_Invalid_Type {
            get {
                return ResourceManager.GetString("CalendarAuthenticationRecord_Invalid_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/calendar-authentication-record/calendar-authentication-record-ok.tlv.
        /// </summary>
        internal static string CalendarAuthenticationRecord_Ok {
            get {
                return ResourceManager.GetString("CalendarAuthenticationRecord_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/calendar-hash-chain/calendar-hash-chain-invalid-extra-tag.tlv.
        /// </summary>
        internal static string CalendarHashChain_Invalid_Extra_Tag {
            get {
                return ResourceManager.GetString("CalendarHashChain_Invalid_Extra_Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/calendar-hash-chain/calendar-hash-chain-invalid-missing-input-hash.tlv.
        /// </summary>
        internal static string CalendarHashChain_Invalid_Missing_Input_Hash {
            get {
                return ResourceManager.GetString("CalendarHashChain_Invalid_Missing_Input_Hash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/calendar-hash-chain/calendar-hash-chain-invalid-missing-links.tlv.
        /// </summary>
        internal static string CalendarHashChain_Invalid_Missing_Links {
            get {
                return ResourceManager.GetString("CalendarHashChain_Invalid_Missing_Links", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/calendar-hash-chain/calendar-hash-chain-invalid-missing-publication-time.tlv.
        /// </summary>
        internal static string CalendarHashChain_Invalid_Missing_Publication_Time {
            get {
                return ResourceManager.GetString("CalendarHashChain_Invalid_Missing_Publication_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/calendar-hash-chain/calendar-hash-chain-invalid-multiple-aggregation-time.tlv.
        /// </summary>
        internal static string CalendarHashChain_Invalid_Multiple_Aggregation_Time {
            get {
                return ResourceManager.GetString("CalendarHashChain_Invalid_Multiple_Aggregation_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/calendar-hash-chain/calendar-hash-chain-invalid-multiple-input-hash.tlv.
        /// </summary>
        internal static string CalendarHashChain_Invalid_Multiple_Input_Hash {
            get {
                return ResourceManager.GetString("CalendarHashChain_Invalid_Multiple_Input_Hash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/calendar-hash-chain/calendar-hash-chain-invalid-multiple-publication-time.tlv.
        /// </summary>
        internal static string CalendarHashChain_Invalid_Multiple_Publication_Time {
            get {
                return ResourceManager.GetString("CalendarHashChain_Invalid_Multiple_Publication_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/calendar-hash-chain/calendar-hash-chain-invalid-type.tlv.
        /// </summary>
        internal static string CalendarHashChain_Invalid_Type {
            get {
                return ResourceManager.GetString("CalendarHashChain_Invalid_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/calendar-hash-chain/calendar-hash-chain-ok.tlv.
        /// </summary>
        internal static string CalendarHashChain_Ok {
            get {
                return ResourceManager.GetString("CalendarHashChain_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/calendar-hash-chain/calendar-hash-chain-ok-changed-algorithm.tlv.
        /// </summary>
        internal static string CalendarHashChain_Ok_Changed_Algorithm {
            get {
                return ResourceManager.GetString("CalendarHashChain_Ok_Changed_Algorithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/calendar-hash-chain/calendar-hash-chain-ok-missing-optionals.tlv.
        /// </summary>
        internal static string CalendarHashChain_Ok_Missing_Optionals {
            get {
                return ResourceManager.GetString("CalendarHashChain_Ok_Missing_Optionals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/testdata.txt.
        /// </summary>
        internal static string DataHasher_TestFile {
            get {
                return ResourceManager.GetString("DataHasher_TestFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LongString1ReallyLongString2EvenLongerString3.
        /// </summary>
        internal static string DataHasher_TestString {
            get {
                return ResourceManager.GetString("DataHasher_TestString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/publication/publicationsfile/ksi-publications.bin.
        /// </summary>
        internal static string KsiPublicationsFile {
            get {
                return ResourceManager.GetString("KsiPublicationsFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/publication/publicationsfile/ksi-publications-2017-12.bin.
        /// </summary>
        internal static string KsiPublicationsFile_201712 {
            get {
                return ResourceManager.GetString("KsiPublicationsFile_201712", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/service/aggregation-response-pdu-with-only-unknown-non-critical-payload.tlv.
        /// </summary>
        internal static string KsiSerice_AggregationResponseUnknownNonCriticalPayload {
            get {
                return ResourceManager.GetString("KsiSerice_AggregationResponseUnknownNonCriticalPayload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/service/aggregation-response-pdu-with-conf.tlv.
        /// </summary>
        internal static string KsiSerice_AggregationResponseWithConf {
            get {
                return ResourceManager.GetString("KsiSerice_AggregationResponseWithConf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/service/aggregation-response-pdu-with-unknown-non-critical-payload.tlv.
        /// </summary>
        internal static string KsiSerice_AggregationResponseWithUnknownNonCriticalPayload {
            get {
                return ResourceManager.GetString("KsiSerice_AggregationResponseWithUnknownNonCriticalPayload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/service/extender-response-with-only-unknown-non-critical-payload.tlv.
        /// </summary>
        internal static string KsiSerice_ExtenderResponseUnkownNonCriticalPayload {
            get {
                return ResourceManager.GetString("KsiSerice_ExtenderResponseUnkownNonCriticalPayload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/service/extend-response-pdu-unknown-non-critical-payload.tlv.
        /// </summary>
        internal static string KsiSerice_ExtendResponseNonCriticalPayload {
            get {
                return ResourceManager.GetString("KsiSerice_ExtendResponseNonCriticalPayload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/service/extend-response-with-conf.tlv.
        /// </summary>
        internal static string KsiSerice_ExtendResponseWithConf {
            get {
                return ResourceManager.GetString("KsiSerice_ExtendResponseWithConf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/service/aggregation-response-pdu-error-payload.tlv.
        /// </summary>
        internal static string KsiService_AggregationResponsePdu_ErrorPayload {
            get {
                return ResourceManager.GetString("KsiService_AggregationResponsePdu_ErrorPayload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/service/aggregation-response-pdu-invalid-signature.tlv.
        /// </summary>
        internal static string KsiService_AggregationResponsePdu_Invalid_Signature {
            get {
                return ResourceManager.GetString("KsiService_AggregationResponsePdu_Invalid_Signature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/service/aggregation-response-pdu-multi-payloads.tlv.
        /// </summary>
        internal static string KsiService_AggregationResponsePdu_Multi_Payloads {
            get {
                return ResourceManager.GetString("KsiService_AggregationResponsePdu_Multi_Payloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/service/aggregation-response-pdu-multi-payloads-including-error.tlv.
        /// </summary>
        internal static string KsiService_AggregationResponsePdu_Multi_Payloads_Including_ErrorPayload {
            get {
                return ResourceManager.GetString("KsiService_AggregationResponsePdu_Multi_Payloads_Including_ErrorPayload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/service/aggregation-response-pdu.tlv.
        /// </summary>
        internal static string KsiService_AggregationResponsePdu_RequestId_1584727637 {
            get {
                return ResourceManager.GetString("KsiService_AggregationResponsePdu_RequestId_1584727637", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/service/aggregation-response-pdu-2.tlv.
        /// </summary>
        internal static string KsiService_AggregationResponsePdu_RequestId_1584727638 {
            get {
                return ResourceManager.GetString("KsiService_AggregationResponsePdu_RequestId_1584727638", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/service/aggregation-response-pdu-with-level-correction-1.tlv.
        /// </summary>
        internal static string KsiService_AggregationResponsePdu_SignedLevel2_LevelCorrection1 {
            get {
                return ResourceManager.GetString("KsiService_AggregationResponsePdu_SignedLevel2_LevelCorrection1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/service/aggregation-response-pdu-signed-zero-bytes.tlv.
        /// </summary>
        internal static string KsiService_AggregationResponsePdu_SignedZeroBytes {
            get {
                return ResourceManager.GetString("KsiService_AggregationResponsePdu_SignedZeroBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/service/aggregation-response-pdu-with-config-and-acknowledgment.tlv.
        /// </summary>
        internal static string KsiService_AggregationResponsePdu_With_Config_And_Acknowledgment {
            get {
                return ResourceManager.GetString("KsiService_AggregationResponsePdu_With_Config_And_Acknowledgment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/service/aggregator-config-response-pdu.tlv.
        /// </summary>
        internal static string KsiService_AggregatorConfigResponsePdu {
            get {
                return ResourceManager.GetString("KsiService_AggregatorConfigResponsePdu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/service/aggregator-config-response-pdu-0x0-int.tlv.
        /// </summary>
        internal static string KsiService_AggregatorConfigResponsePdu_0x0_Int {
            get {
                return ResourceManager.GetString("KsiService_AggregatorConfigResponsePdu_0x0_Int", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/service/aggregator-config-response-pdu-with-acknowledgment.tlv.
        /// </summary>
        internal static string KsiService_AggregatorConfigResponsePdu_With_Acknowledgment {
            get {
                return ResourceManager.GetString("KsiService_AggregatorConfigResponsePdu_With_Acknowledgment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/service/extender-config-response-pdu.tlv.
        /// </summary>
        internal static string KsiService_ExtenderConfigResponsePdu {
            get {
                return ResourceManager.GetString("KsiService_ExtenderConfigResponsePdu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/service/extender-response-pdu-error-payload.tlv.
        /// </summary>
        internal static string KsiService_ExtenderResponsePdu_ErrorPayload {
            get {
                return ResourceManager.GetString("KsiService_ExtenderResponsePdu_ErrorPayload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/service/extend-response-pdu-invalid-signature.tlv.
        /// </summary>
        internal static string KsiService_ExtendResponsePdu_Invalid_Signature {
            get {
                return ResourceManager.GetString("KsiService_ExtendResponsePdu_Invalid_Signature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/service/extend-response-pdu-multi-payloads.tlv.
        /// </summary>
        internal static string KsiService_ExtendResponsePdu_Multi_Payloads {
            get {
                return ResourceManager.GetString("KsiService_ExtendResponsePdu_Multi_Payloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/service/extend-response-pdu-multi-payloads-including-error.tlv.
        /// </summary>
        internal static string KsiService_ExtendResponsePdu_Multi_Payloads_Including_ErrorPayload {
            get {
                return ResourceManager.GetString("KsiService_ExtendResponsePdu_Multi_Payloads_Including_ErrorPayload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/service/extend-response-pdu-status-17.tlv.
        /// </summary>
        internal static string KsiService_ExtendResponsePdu_NonZeroPayloadStatus {
            get {
                return ResourceManager.GetString("KsiService_ExtendResponsePdu_NonZeroPayloadStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/service/extend-response-pdu-2.tlv.
        /// </summary>
        internal static string KsiService_ExtendResponsePdu_RequestId_1043101454 {
            get {
                return ResourceManager.GetString("KsiService_ExtendResponsePdu_RequestId_1043101454", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/service/extend-response-pdu.tlv.
        /// </summary>
        internal static string KsiService_ExtendResponsePdu_RequestId_1043101455 {
            get {
                return ResourceManager.GetString("KsiService_ExtendResponsePdu_RequestId_1043101455", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/service/legacy-aggregation-response-pdu.tlv.
        /// </summary>
        internal static string KsiService_LegacyAggregationResponsePdu {
            get {
                return ResourceManager.GetString("KsiService_LegacyAggregationResponsePdu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/service/legacy-aggregation-response-pdu-0x0-int.tlv.
        /// </summary>
        internal static string KsiService_LegacyAggregationResponsePdu_0x0_Int {
            get {
                return ResourceManager.GetString("KsiService_LegacyAggregationResponsePdu_0x0_Int", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/service/legacy-extend-response-pdu.tlv.
        /// </summary>
        internal static string KsiService_LegacyExtendResponsePdu {
            get {
                return ResourceManager.GetString("KsiService_LegacyExtendResponsePdu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/service/legacy-extend-response-pdu-status-17.tlv.
        /// </summary>
        internal static string KsiService_LegacyExtendResponsePdu_NonZeroPayloadStatus {
            get {
                return ResourceManager.GetString("KsiService_LegacyExtendResponsePdu_NonZeroPayloadStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/ksi-signature/ksi-signature-invalid-aggregation-chain-aggregation-time-mismatch.tlv.
        /// </summary>
        internal static string KsiSignature_Invalid_Aggregation_Chain_Aggregation_Time_Mismatch {
            get {
                return ResourceManager.GetString("KsiSignature_Invalid_Aggregation_Chain_Aggregation_Time_Mismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/ksi-signature/ksi-signature-invalid-aggregation-chain-index-mismatch.tlv.
        /// </summary>
        internal static string KsiSignature_Invalid_Aggregation_Chain_Index_Mismatch {
            get {
                return ResourceManager.GetString("KsiSignature_Invalid_Aggregation_Chain_Index_Mismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/ksi-signature/ksi-signature-invalid-aggregation-chain-index-mismatch-prev.tlv.
        /// </summary>
        internal static string KsiSignature_Invalid_Aggregation_Chain_Index_Mismatch_Prev {
            get {
                return ResourceManager.GetString("KsiSignature_Invalid_Aggregation_Chain_Index_Mismatch_Prev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/ksi-signature/ksi-signature-invalid-aggregation-chain-index-mismatch-prev-2.tlv.
        /// </summary>
        internal static string KsiSignature_Invalid_Aggregation_Chain_Index_Mismatch_Prev2 {
            get {
                return ResourceManager.GetString("KsiSignature_Invalid_Aggregation_Chain_Index_Mismatch_Prev2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/ksi-signature/ksi-signature-invalid-aggregation-chain-input-hash.tlv.
        /// </summary>
        internal static string KsiSignature_Invalid_Aggregation_Chain_Input_Hash {
            get {
                return ResourceManager.GetString("KsiSignature_Invalid_Aggregation_Chain_Input_Hash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/ksi-signature/ksi-signature-invalid-calendar-auth-record-pkcs7-signature.tlv.
        /// </summary>
        internal static string KsiSignature_Invalid_Calendar_Auth_Record_Pkcs7_Signature {
            get {
                return ResourceManager.GetString("KsiSignature_Invalid_Calendar_Auth_Record_Pkcs7_Signature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/ksi-signature/ksi-signature-invalid-calendar-auth-record-pkcs7-signature-modified-bytes.tlv.
        /// </summary>
        internal static string KsiSignature_Invalid_Calendar_Auth_Record_Pkcs7_Signature_Modified_Bytes {
            get {
                return ResourceManager.GetString("KsiSignature_Invalid_Calendar_Auth_Record_Pkcs7_Signature_Modified_Bytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/ksi-signature/ksi-signature-invalid-calendar-auth-record-pkcs7-signature-cert-not-valid.tlv.
        /// </summary>
        internal static string KsiSignature_Invalid_Calendar_Auth_Record_Pkcs7_Signature_Not_Valid_Cert {
            get {
                return ResourceManager.GetString("KsiSignature_Invalid_Calendar_Auth_Record_Pkcs7_Signature_Not_Valid_Cert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/ksi-signature/ksi-signature-invalid-calendar-authentication-record-invalid-publication-hash.tlv.
        /// </summary>
        internal static string KsiSignature_Invalid_Calendar_Authentication_Record_Invalid_Publication_Hash {
            get {
                return ResourceManager.GetString("KsiSignature_Invalid_Calendar_Authentication_Record_Invalid_Publication_Hash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/ksi-signature/ksi-signature-invalid-calendar-authentication-record-invalid-publication-time.tlv.
        /// </summary>
        internal static string KsiSignature_Invalid_Calendar_Authentication_Record_Invalid_Publication_Time {
            get {
                return ResourceManager.GetString("KsiSignature_Invalid_Calendar_Authentication_Record_Invalid_Publication_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/ksi-signature/ksi-signature-invalid-calendar-authentication-record-invalid-signature.tlv.
        /// </summary>
        internal static string KsiSignature_Invalid_Calendar_Authentication_Record_Invalid_Signature {
            get {
                return ResourceManager.GetString("KsiSignature_Invalid_Calendar_Authentication_Record_Invalid_Signature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/ksi-signature/ksi-signature-invalid-calendar-hash-chain-input-hash.tlv.
        /// </summary>
        internal static string KsiSignature_Invalid_Calendar_Chain_Input_Hash {
            get {
                return ResourceManager.GetString("KsiSignature_Invalid_Calendar_Chain_Input_Hash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/ksi-signature/ksi-signature-invalid-calendar-hash-chain-publication-time.tlv.
        /// </summary>
        internal static string KsiSignature_Invalid_Calendar_Chain_Publication_Time {
            get {
                return ResourceManager.GetString("KsiSignature_Invalid_Calendar_Chain_Publication_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/ksi-signature/ksi-signature-invalid-calendar-hash-chain-registration-time.tlv.
        /// </summary>
        internal static string KsiSignature_Invalid_Calendar_Chain_Registration_Time {
            get {
                return ResourceManager.GetString("KsiSignature_Invalid_Calendar_Chain_Registration_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/ksi-signature/ksi-signature-invalid-contain-both-publication-record-and-calendar-authentication-record.tlv.
        /// </summary>
        internal static string KsiSignature_Invalid_Contain_Publication_Record_And_Calendar_Authentication_Record {
            get {
                return ResourceManager.GetString("KsiSignature_Invalid_Contain_Publication_Record_And_Calendar_Authentication_Recor" +
                        "d", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/ksi-signature/ksi-signature-invalid-extra-tag.tlv.
        /// </summary>
        internal static string KsiSignature_Invalid_Extra_Tag {
            get {
                return ResourceManager.GetString("KsiSignature_Invalid_Extra_Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/ksi-signature/ksi-signature-invalid-first-aggregation-chain-index-length.tlv.
        /// </summary>
        internal static string KsiSignature_Invalid_First_Aggregation_Chain_Index_Length {
            get {
                return ResourceManager.GetString("KsiSignature_Invalid_First_Aggregation_Chain_Index_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/ksi-signature/ksi-signature-invalid-hash-algorithm.tlv.
        /// </summary>
        internal static string KsiSignature_Invalid_Hash_Algorithm {
            get {
                return ResourceManager.GetString("KsiSignature_Invalid_Hash_Algorithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/ksi-signature/ksi-signature-invalid-missing-aggregation-hash-chains.tlv.
        /// </summary>
        internal static string KsiSignature_Invalid_Missing_Aggregation_Hash_Chain {
            get {
                return ResourceManager.GetString("KsiSignature_Invalid_Missing_Aggregation_Hash_Chain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/ksi-signature/ksi-signature-invalid-missing-calendar-auth-record.tlv.
        /// </summary>
        internal static string KsiSignature_Invalid_Missing_Calendar_Authentication_Record {
            get {
                return ResourceManager.GetString("KsiSignature_Invalid_Missing_Calendar_Authentication_Record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/ksi-signature/ksi-signature-Invalid-Missing-calendar-hash-chain.tlv.
        /// </summary>
        internal static string KsiSignature_Invalid_Missing_Calendar_Hash_Chain {
            get {
                return ResourceManager.GetString("KsiSignature_Invalid_Missing_Calendar_Hash_Chain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/ksi-signature/ksi-signature-invalid-multiple-calendar-authentication-records.tlv.
        /// </summary>
        internal static string KsiSignature_Invalid_Multiple_Calendar_Authentication_Records {
            get {
                return ResourceManager.GetString("KsiSignature_Invalid_Multiple_Calendar_Authentication_Records", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/ksi-signature/ksi-signature-invalid-multiple-calendar-hash-chains.tlv.
        /// </summary>
        internal static string KsiSignature_Invalid_Multiple_Calendar_Hash_Chains {
            get {
                return ResourceManager.GetString("KsiSignature_Invalid_Multiple_Calendar_Hash_Chains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/ksi-signature/ksi-signature-invalid-multiple-publication-records.tlv.
        /// </summary>
        internal static string KsiSignature_Invalid_Multiple_Publication_Records {
            get {
                return ResourceManager.GetString("KsiSignature_Invalid_Multiple_Publication_Records", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/ksi-signature/ksi-signature-invalid-multiple-rfc3161-records.tlv.
        /// </summary>
        internal static string KsiSignature_Invalid_Multiple_Rfc_3161_Records {
            get {
                return ResourceManager.GetString("KsiSignature_Invalid_Multiple_Rfc_3161_Records", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/ksi-signature/ksi-signature-invalid-not-valid-cert.tlv.
        /// </summary>
        internal static string KsiSignature_Invalid_Not_Valid_Cert {
            get {
                return ResourceManager.GetString("KsiSignature_Invalid_Not_Valid_Cert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/ksi-signature/ksi-signature-invalid-rfc3161-aggregation-time-mismatch.tlv.
        /// </summary>
        internal static string KsiSignature_Invalid_Rfc3161_Aggregation_Time_Mismatch {
            get {
                return ResourceManager.GetString("KsiSignature_Invalid_Rfc3161_Aggregation_Time_Mismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/ksi-signature/ksi-signature-invalid-chain-index-mismatch.tlv.
        /// </summary>
        internal static string KsiSignature_Invalid_Rfc3161_Chain_Index_Mismatch {
            get {
                return ResourceManager.GetString("KsiSignature_Invalid_Rfc3161_Chain_Index_Mismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/ksi-signature/ksi-signature-invalid-type.tlv.
        /// </summary>
        internal static string KsiSignature_Invalid_Type {
            get {
                return ResourceManager.GetString("KsiSignature_Invalid_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/ksi-signature/ksi-signature-invalid-aggregation-root-hash.tlv.
        /// </summary>
        internal static string KsiSignature_Invalid_With_Invalid_Aggregation_Root_Hash {
            get {
                return ResourceManager.GetString("KsiSignature_Invalid_With_Invalid_Aggregation_Root_Hash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/ksi-signature/ksi-signature-invalid-with-invalid-publication-record-hash.tlv.
        /// </summary>
        internal static string KsiSignature_Invalid_With_Invalid_Publication_Record_Hash {
            get {
                return ResourceManager.GetString("KsiSignature_Invalid_With_Invalid_Publication_Record_Hash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/ksi-signature/ksi-signature-invalid-with-invalid-publication-record-time.tlv.
        /// </summary>
        internal static string KsiSignature_Invalid_With_Invalid_Publication_Record_Time {
            get {
                return ResourceManager.GetString("KsiSignature_Invalid_With_Invalid_Publication_Record_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/ksi-signature/legacy-ksi-signature-invalid-input.tlv.
        /// </summary>
        internal static string KsiSignature_Legacy_Invalid_Input {
            get {
                return ResourceManager.GetString("KsiSignature_Legacy_Invalid_Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/ksi-signature/legacy-ksi-signature-ok.tlv.
        /// </summary>
        internal static string KsiSignature_Legacy_Ok {
            get {
                return ResourceManager.GetString("KsiSignature_Legacy_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/ksi-signature/legacy-ksi-signature-ok-with-publication-record.tlv.
        /// </summary>
        internal static string KsiSignature_Legacy_Ok_With_Publication_Record {
            get {
                return ResourceManager.GetString("KsiSignature_Legacy_Ok_With_Publication_Record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/ksi-signature/ksi-siganture-obsolete-calendar-algo-2016-01.tlv.
        /// </summary>
        internal static string KsiSignature_Obsolete_Calendar_Chain_Algorithm_2016 {
            get {
                return ResourceManager.GetString("KsiSignature_Obsolete_Calendar_Chain_Algorithm_2016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/ksi-signature/ksi-siganture-obsolete-calendar-algo-2017.tlv.
        /// </summary>
        internal static string KsiSignature_Obsolete_Calendar_Chain_Algorithm_2017 {
            get {
                return ResourceManager.GetString("KsiSignature_Obsolete_Calendar_Chain_Algorithm_2017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/ksi-signature/ksi-signature-ok.tlv.
        /// </summary>
        internal static string KsiSignature_Ok {
            get {
                return ResourceManager.GetString("KsiSignature_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/ksi-signature/ksi-signature-ok-2017-12-19.tlv.
        /// </summary>
        internal static string KsiSignature_Ok_20171219 {
            get {
                return ResourceManager.GetString("KsiSignature_Ok_20171219", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/ksi-signature/ksi-signature-ok-calendar-auth-record-pkcs7-signature.tlv.
        /// </summary>
        internal static string KsiSignature_Ok_Calendar_Auth_Record_Pkcs7_Signature {
            get {
                return ResourceManager.GetString("KsiSignature_Ok_Calendar_Auth_Record_Pkcs7_Signature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/ksi-signature/ksi-signature-ok-extended.tlv.
        /// </summary>
        internal static string KsiSignature_Ok_Extended {
            get {
                return ResourceManager.GetString("KsiSignature_Ok_Extended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/ksi-signature/ksi-signature-ok-identity.tlv.
        /// </summary>
        internal static string KsiSignature_Ok_Identity {
            get {
                return ResourceManager.GetString("KsiSignature_Ok_Identity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/ksi-signature/ksi-signature-level-correction-3.tlv.
        /// </summary>
        internal static string KsiSignature_Ok_LevelCorrection3 {
            get {
                return ResourceManager.GetString("KsiSignature_Ok_LevelCorrection3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/ksi-signature/ksi-signature-ok-Missing-publication-record-and-calendar-authentication-record.tlv.
        /// </summary>
        internal static string KsiSignature_Ok_Missing_Publication_Record_And_Calendar_Authentication_Record {
            get {
                return ResourceManager.GetString("KsiSignature_Ok_Missing_Publication_Record_And_Calendar_Authentication_Record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/ksi-signature/ksi-signature-ok-new.tlv.
        /// </summary>
        internal static string KsiSignature_Ok_New {
            get {
                return ResourceManager.GetString("KsiSignature_Ok_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/shared/valid-signatures/signature-only-aggregation-chains.ksig.
        /// </summary>
        internal static string KsiSignature_Ok_Only_Aggregtion_Chains {
            get {
                return ResourceManager.GetString("KsiSignature_Ok_Only_Aggregtion_Chains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/ksi-signature/ksi-signature-ok-with-mixed-aggregation-chains.tlv.
        /// </summary>
        internal static string KsiSignature_Ok_With_Mixed_Aggregation_Chains {
            get {
                return ResourceManager.GetString("KsiSignature_Ok_With_Mixed_Aggregation_Chains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/ksi-signature/ksi-signature-ok-with-publication-record.tlv.
        /// </summary>
        internal static string KsiSignature_Ok_With_Publication_Record {
            get {
                return ResourceManager.GetString("KsiSignature_Ok_With_Publication_Record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/rfc3161-record/rfc3161-sha1-as-input-hash-2016-01.tlv.
        /// </summary>
        internal static string KsiSignature_Rfc3161Record_Sha1InputHashAlgorithm_2016 {
            get {
                return ResourceManager.GetString("KsiSignature_Rfc3161Record_Sha1InputHashAlgorithm_2016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/rfc3161-record/rfc3161-sha1-as-input-hash-2017.tlv.
        /// </summary>
        internal static string KsiSignature_Rfc3161Record_Sha1InputHashAlgorithm_2017 {
            get {
                return ResourceManager.GetString("KsiSignature_Rfc3161Record_Sha1InputHashAlgorithm_2017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/rfc3161-record/rfc3161-sha1-as-output-hash-2016-01.tlv.
        /// </summary>
        internal static string KsiSignature_Rfc3161Record_Sha1OutputHashAlgorithm_2016 {
            get {
                return ResourceManager.GetString("KsiSignature_Rfc3161Record_Sha1OutputHashAlgorithm_2016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/rfc3161-record/rfc3161-sha1-as-output-hash-2017.tlv.
        /// </summary>
        internal static string KsiSignature_Rfc3161Record_Sha1OutputHashAlgorithm_2017 {
            get {
                return ResourceManager.GetString("KsiSignature_Rfc3161Record_Sha1OutputHashAlgorithm_2017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/rfc3161-record/rfc3161-sha1-in-sig-atr-2016-01.tlv.
        /// </summary>
        internal static string KsiSignature_Rfc3161Record_Sha1SignedAttrAlgorithm_2016 {
            get {
                return ResourceManager.GetString("KsiSignature_Rfc3161Record_Sha1SignedAttrAlgorithm_2016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/rfc3161-record/rfc3161-sha1-in-sig-atr-2017.tlv.
        /// </summary>
        internal static string KsiSignature_Rfc3161Record_Sha1SignedAttrAlgorithm_2017 {
            get {
                return ResourceManager.GetString("KsiSignature_Rfc3161Record_Sha1SignedAttrAlgorithm_2017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/rfc3161-record/rfc3161-sha1-in-tst-algo-2016-01.tlv.
        /// </summary>
        internal static string KsiSignature_Rfc3161Record_Sha1TstInfoAlgorithm_2016 {
            get {
                return ResourceManager.GetString("KsiSignature_Rfc3161Record_Sha1TstInfoAlgorithm_2016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/rfc3161-record/rfc3161-sha1-in-tst-algo-2017.tlv.
        /// </summary>
        internal static string KsiSignature_Rfc3161Record_Sha1TstInfoAlgorithm_2017 {
            get {
                return ResourceManager.GetString("KsiSignature_Rfc3161Record_Sha1TstInfoAlgorithm_2017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/ksi-signature/sha1-as-aggregation-algo-2016-01.tlv.
        /// </summary>
        internal static string KsiSignature_Sha1AggregationChainAlgorithm_2016 {
            get {
                return ResourceManager.GetString("KsiSignature_Sha1AggregationChainAlgorithm_2016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/ksi-signature/sha1-as-aggregation-algo-2017.tlv.
        /// </summary>
        internal static string KsiSignature_Sha1AggregationChainAlgorithm_2017 {
            get {
                return ResourceManager.GetString("KsiSignature_Sha1AggregationChainAlgorithm_2017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/ksi-signature/sha1-as-calendar-algo-2016-01.tlv.
        /// </summary>
        internal static string KsiSignature_Sha1CalendarLeftLinkAlgorithm_2016 {
            get {
                return ResourceManager.GetString("KsiSignature_Sha1CalendarLeftLinkAlgorithm_2016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/ksi-signature/sha1-as-calendar-algo-2017.tlv.
        /// </summary>
        internal static string KsiSignature_Sha1CalendarLeftLinkAlgorithm_2017 {
            get {
                return ResourceManager.GetString("KsiSignature_Sha1CalendarLeftLinkAlgorithm_2017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/ksi-signature/sha1-as-input-algo-2016-01.tlv.
        /// </summary>
        internal static string KsiSignature_Sha1InputAlgorithm_2016 {
            get {
                return ResourceManager.GetString("KsiSignature_Sha1InputAlgorithm_2016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/ksi-signature/sha1-as-input-algo-2017.tlv.
        /// </summary>
        internal static string KsiSignature_Sha1InputAlgorithm_2017 {
            get {
                return ResourceManager.GetString("KsiSignature_Sha1InputAlgorithm_2017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/trust/pkitrustprovider/custom-cert.pem.
        /// </summary>
        internal static string PkiTrustProvider_CustomCert {
            get {
                return ResourceManager.GetString("PkiTrustProvider_CustomCert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/trust/pkitrustprovider/custom-cert-expired.cer.
        /// </summary>
        internal static string PkiTrustProvider_CustomCertExpired {
            get {
                return ResourceManager.GetString("PkiTrustProvider_CustomCertExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/trust/pkitrustprovider/custom-cert-invalid.pem.
        /// </summary>
        internal static string PkiTrustProvider_CustomCertInvalid {
            get {
                return ResourceManager.GetString("PkiTrustProvider_CustomCertInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/trust/pkitrustprovider/identrust.pem.
        /// </summary>
        internal static string PkiTrustProvider_IdenTrustCert {
            get {
                return ResourceManager.GetString("PkiTrustProvider_IdenTrustCert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/trust/pkitrustprovider/pubs-file-custom-cert.bin.
        /// </summary>
        internal static string PkiTrustProvider_PubsFileCustomCert {
            get {
                return ResourceManager.GetString("PkiTrustProvider_PubsFileCustomCert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/trust/pkitrustprovider/pubs-file-custom-cert-expired.bin.
        /// </summary>
        internal static string PkiTrustProvider_PubsFileCustomCertExpired {
            get {
                return ResourceManager.GetString("PkiTrustProvider_PubsFileCustomCertExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/rfc3161-record/rfc3161-record-invalid-extra-tag.tlv.
        /// </summary>
        internal static string Rfc3161Record_Invalid_Extra_Tag {
            get {
                return ResourceManager.GetString("Rfc3161Record_Invalid_Extra_Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/rfc3161-record/rfc3161-record-invalid-missing-aggregation-time.tlv.
        /// </summary>
        internal static string Rfc3161Record_Invalid_Missing_Aggregation_Time {
            get {
                return ResourceManager.GetString("Rfc3161Record_Invalid_Missing_Aggregation_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/rfc3161-record/rfc3161-record-invalid-missing-chain-index.tlv.
        /// </summary>
        internal static string Rfc3161Record_Invalid_Missing_Chain_Index {
            get {
                return ResourceManager.GetString("Rfc3161Record_Invalid_Missing_Chain_Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/rfc3161-record/rfc3161-record-invalid-missing-input-hash.tlv.
        /// </summary>
        internal static string Rfc3161Record_Invalid_Missing_Input_Hash {
            get {
                return ResourceManager.GetString("Rfc3161Record_Invalid_Missing_Input_Hash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/rfc3161-record/rfc3161-record-invalid-missing-signed-attributes-algorithm.tlv.
        /// </summary>
        internal static string Rfc3161Record_Invalid_Missing_Signed_Attributes_Algorithm {
            get {
                return ResourceManager.GetString("Rfc3161Record_Invalid_Missing_Signed_Attributes_Algorithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/rfc3161-record/rfc3161-record-invalid-missing-signed-attributes-prefix.tlv.
        /// </summary>
        internal static string Rfc3161Record_Invalid_Missing_Signed_Attributes_Prefix {
            get {
                return ResourceManager.GetString("Rfc3161Record_Invalid_Missing_Signed_Attributes_Prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/rfc3161-record/rfc3161-record-invalid-missing-signed-attributes-suffix.tlv.
        /// </summary>
        internal static string Rfc3161Record_Invalid_Missing_Signed_Attributes_Suffix {
            get {
                return ResourceManager.GetString("Rfc3161Record_Invalid_Missing_Signed_Attributes_Suffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/rfc3161-record/rfc3161-record-invalid-missing-tstinfo-algorithm.tlv.
        /// </summary>
        internal static string Rfc3161Record_Invalid_Missing_TstInfo_Algorithm {
            get {
                return ResourceManager.GetString("Rfc3161Record_Invalid_Missing_TstInfo_Algorithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/rfc3161-record/rfc3161-record-invalid-missing-tstinfo-prefix.tlv.
        /// </summary>
        internal static string Rfc3161Record_Invalid_Missing_TstInfo_Prefix {
            get {
                return ResourceManager.GetString("Rfc3161Record_Invalid_Missing_TstInfo_Prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/rfc3161-record/rfc3161-record-invalid-missing-tstinfo-suffix.tlv.
        /// </summary>
        internal static string Rfc3161Record_Invalid_Missing_TstInfo_Suffix {
            get {
                return ResourceManager.GetString("Rfc3161Record_Invalid_Missing_TstInfo_Suffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/rfc3161-record/rfc3161-record-invalid-multiple-aggregation-time.tlv.
        /// </summary>
        internal static string Rfc3161Record_Invalid_Multiple_Aggregation_Time {
            get {
                return ResourceManager.GetString("Rfc3161Record_Invalid_Multiple_Aggregation_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/rfc3161-record/rfc3161-record-invalid-multiple-input-hash.tlv.
        /// </summary>
        internal static string Rfc3161Record_Invalid_Multiple_Input_Hash {
            get {
                return ResourceManager.GetString("Rfc3161Record_Invalid_Multiple_Input_Hash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/rfc3161-record/rfc3161-record-invalid-multiple-signed-attributes-algorithm.tlv.
        /// </summary>
        internal static string Rfc3161Record_Invalid_Multiple_Signed_Attributes_Algorithm {
            get {
                return ResourceManager.GetString("Rfc3161Record_Invalid_Multiple_Signed_Attributes_Algorithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/rfc3161-record/rfc3161-record-invalid-multiple-signed-attributes-prefix.tlv.
        /// </summary>
        internal static string Rfc3161Record_Invalid_Multiple_Signed_Attributes_Prefix {
            get {
                return ResourceManager.GetString("Rfc3161Record_Invalid_Multiple_Signed_Attributes_Prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/rfc3161-record/rfc3161-record-invalid-multiple-signed-attributes-suffix.tlv.
        /// </summary>
        internal static string Rfc3161Record_Invalid_Multiple_Signed_Attributes_Suffix {
            get {
                return ResourceManager.GetString("Rfc3161Record_Invalid_Multiple_Signed_Attributes_Suffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/rfc3161-record/rfc3161-record-invalid-multiple-tstinfo-algorithm.tlv.
        /// </summary>
        internal static string Rfc3161Record_Invalid_Multiple_TstInfo_Algorithm {
            get {
                return ResourceManager.GetString("Rfc3161Record_Invalid_Multiple_TstInfo_Algorithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/rfc3161-record/rfc3161-record-invalid-multiple-tstinfo-prefix.tlv.
        /// </summary>
        internal static string Rfc3161Record_Invalid_Multiple_TstInfo_Prefix {
            get {
                return ResourceManager.GetString("Rfc3161Record_Invalid_Multiple_TstInfo_Prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/rfc3161-record/rfc3161-record-invalid-multiple-tstinfo-suffix.tlv.
        /// </summary>
        internal static string Rfc3161Record_Invalid_Multiple_TstInfo_Suffix {
            get {
                return ResourceManager.GetString("Rfc3161Record_Invalid_Multiple_TstInfo_Suffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/rfc3161-record/rfc3161-record-invalid-type.tlv.
        /// </summary>
        internal static string Rfc3161Record_Invalid_Type {
            get {
                return ResourceManager.GetString("Rfc3161Record_Invalid_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/rfc3161-record/rfc3161-record-ok.tlv.
        /// </summary>
        internal static string Rfc3161Record_Ok {
            get {
                return ResourceManager.GetString("Rfc3161Record_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/signaturedata/signature-data-invalid-certificate-id-missing.tlv.
        /// </summary>
        internal static string SignatureData_Invalid_Certificate_Id_Missing {
            get {
                return ResourceManager.GetString("SignatureData_Invalid_Certificate_Id_Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/signaturedata/signature-data-invalid-extra-tag.tlv.
        /// </summary>
        internal static string SignatureData_Invalid_Extra_Tag {
            get {
                return ResourceManager.GetString("SignatureData_Invalid_Extra_Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/signaturedata/signature-data-invalid-leading-zero.tlv.
        /// </summary>
        internal static string SignatureData_Invalid_Leading_Zero {
            get {
                return ResourceManager.GetString("SignatureData_Invalid_Leading_Zero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/signaturedata/signature-data-invalid-multiple-certificate-id.tlv.
        /// </summary>
        internal static string SignatureData_Invalid_Multiple_Certificate_Id {
            get {
                return ResourceManager.GetString("SignatureData_Invalid_Multiple_Certificate_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/signaturedata/signature-data-invalid-multiple-certificate-rep-uri.tlv.
        /// </summary>
        internal static string SignatureData_Invalid_Multiple_Certificate_Rep_Uri {
            get {
                return ResourceManager.GetString("SignatureData_Invalid_Multiple_Certificate_Rep_Uri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/signaturedata/signature-data-invalid-multiple-type.tlv.
        /// </summary>
        internal static string SignatureData_Invalid_Multiple_Signature_Type {
            get {
                return ResourceManager.GetString("SignatureData_Invalid_Multiple_Signature_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/signaturedata/signature-data-invalid-multiple-value.tlv.
        /// </summary>
        internal static string SignatureData_Invalid_Multiple_Signature_Value {
            get {
                return ResourceManager.GetString("SignatureData_Invalid_Multiple_Signature_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/signaturedata/signature-data-invalid-type-missing.tlv.
        /// </summary>
        internal static string SignatureData_Invalid_Signature_Type_Missing {
            get {
                return ResourceManager.GetString("SignatureData_Invalid_Signature_Type_Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/signaturedata/signature-data-invalid-value-missing.tlv.
        /// </summary>
        internal static string SignatureData_Invalid_Signature_Value_Missing {
            get {
                return ResourceManager.GetString("SignatureData_Invalid_Signature_Value_Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/signaturedata/signature-data-invalid-type.tlv.
        /// </summary>
        internal static string SignatureData_Invalid_Wrong_Type {
            get {
                return ResourceManager.GetString("SignatureData_Invalid_Wrong_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/signaturedata/signature-data-ok.tlv.
        /// </summary>
        internal static string SignatureData_Ok {
            get {
                return ResourceManager.GetString("SignatureData_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/signature/signaturedata/signature-data-ok-no-uri.tlv.
        /// </summary>
        internal static string SignatureData_Ok_No_Uri {
            get {
                return ResourceManager.GetString("SignatureData_Ok_No_Uri", resourceCulture);
            }
        }
    }
}
